site_name: FRC Software Guide
theme:
  name: material  # This gives it the professional WPILib-style look
  palette:
    primary: indigo # You can change this to your team's color
    accent: indigo

nav:
  - Home: index.md
  - 1 Learn Java:
      - 1.1 WPILib: 1.1.md
      - 1.2 VSCode: 1.2.md
      - 1.3 Java Program: 1.3.md
      - 1.4 Variables: 1.4.md
      - 1.5 Logic: 1.5.md
      - 1.6 Arrays: 1.6.md
      - 1.7 Methods: 1.7.md
      - 1.8 Scanner: 1.8.md
      - 1.9 Classes: 1.9.md
      - 1.10 File Organization: 1.10.md
      - 1.11 Enums: 1.11.md
      - 1.12 Math Library: 1.12.md
      - 1.13 Project: 1.13.md
      - 1.14 Suppliers: 1.14.md
  - 2 GitHub:
      - 2.1 Create Account: 2.1.md
      - 2.2 Install Git: 2.2.md
      - 2.3 GitHub Organization: 2.3.md
      - 2.4 Repository: 2.4.md
      - 2.5 Cloning: 2.5.md
      - 2.6 Branches: 2.6.md
      - 2.7 README.md: 2.7.md
      - 2.8 Issues: 2.8.md
      - 2.9 Rebases: 2.9.md
  - 3 Subsystems:
      - 3.1 Robot Project: 3.1.md
      - 3.2 Subsystem Class: 3.2.md
      - 3.3 Subsystem Structure: 3.3.md
      - 3.4 Closed Loop: 3.4.md
      - 3.5 Motor Object: 3.5.md
      - 3.6 Creating a Subsystem: 
          - 3.6.1 Linear Mechanism: 3.6.1.md
          - 3.6.2 Angular Pos Mechanism: 3.6.2.md
          - 3.6.3 Angular Vel Mechanism: 3.6.3.md
  - 4 Subsystems:
      - 4.1 Advantage Kit: 4.1.md
      - 4.2 Advantage Scope Installation: 4.2.md
      - 4.3 Units: 4.3.md
      - 4.4 Tunable Numbers: 4.4.md
      - 4.5 Sensors: 4.5.md
  - 5 Commands:
      - 5.1 Creating Commands: 5.1.md
      - 5.2 Running Commands: 5.2.md
      - 5.3 Elastic: 5.3.md
      - 5.4 Running the Mech: 5.4.md
      - 5.5 Next Steps: 5.5.md
  - 6 Drivetrain:
      - 6.1 Swerve: 6.1.md
      - 6.2 Mecanum: 6.2.md
      - 6.3 Differential (Tank): 6.3.md
  - 7 Robot Vision:
      - 7.1 Sample: 7.1.md
  - 8 Simulation:
      - 8.1 Sample: 8.1.md
  - 9 State Machines:
      - 9.1 Sample: 9.1.md
  - 10 Autonomous:
      - 10.1 Choreo: 10.1.md
      - 10.2 On-the-fly gen: 10.2.md
  - 11 State-Based Action:
      - 11.1 Sample: 11.1.md